# Generated by Django 5.2.8 on 2025-11-22 03:13

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('complete_name', models.CharField(max_length=255)),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('cellphone', encrypted_model_fields.fields.EncryptedCharField()),
            ],
        ),
        migrations.CreateModel(
            name='Avaliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('comment', models.TextField()),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.marketplace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
