# Generated by Django 5.2.8 on 2025-12-02 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_marketplace_marketer_alter_products_marketer'),
        ('marketplace', '0004_alter_products_marketer'),
    ]

    operations = [
    ]
