var namespacepygments_1_1styles =
[
    [ "_mapping", "namespacepygments_1_1styles_1_1__mapping.html", [
      [ "STYLES", "namespacepygments_1_1styles_1_1__mapping.html#a876a5c1d5152fe3115f6b294ef725c03", null ]
    ] ],
    [ "abap", "namespacepygments_1_1styles_1_1abap.html", "namespacepygments_1_1styles_1_1abap" ],
    [ "algol", "namespacepygments_1_1styles_1_1algol.html", "namespacepygments_1_1styles_1_1algol" ],
    [ "algol_nu", "namespacepygments_1_1styles_1_1algol__nu.html", "namespacepygments_1_1styles_1_1algol__nu" ],
    [ "arduino", "namespacepygments_1_1styles_1_1arduino.html", "namespacepygments_1_1styles_1_1arduino" ],
    [ "autumn", "namespacepygments_1_1styles_1_1autumn.html", "namespacepygments_1_1styles_1_1autumn" ],
    [ "borland", "namespacepygments_1_1styles_1_1borland.html", "namespacepygments_1_1styles_1_1borland" ],
    [ "bw", "namespacepygments_1_1styles_1_1bw.html", "namespacepygments_1_1styles_1_1bw" ],
    [ "coffee", "namespacepygments_1_1styles_1_1coffee.html", "namespacepygments_1_1styles_1_1coffee" ],
    [ "colorful", "namespacepygments_1_1styles_1_1colorful.html", "namespacepygments_1_1styles_1_1colorful" ],
    [ "default", "namespacepygments_1_1styles_1_1default.html", "namespacepygments_1_1styles_1_1default" ],
    [ "dracula", "namespacepygments_1_1styles_1_1dracula.html", "namespacepygments_1_1styles_1_1dracula" ],
    [ "emacs", "namespacepygments_1_1styles_1_1emacs.html", "namespacepygments_1_1styles_1_1emacs" ],
    [ "friendly", "namespacepygments_1_1styles_1_1friendly.html", "namespacepygments_1_1styles_1_1friendly" ],
    [ "friendly_grayscale", "namespacepygments_1_1styles_1_1friendly__grayscale.html", "namespacepygments_1_1styles_1_1friendly__grayscale" ],
    [ "fruity", "namespacepygments_1_1styles_1_1fruity.html", "namespacepygments_1_1styles_1_1fruity" ],
    [ "gh_dark", "namespacepygments_1_1styles_1_1gh__dark.html", "namespacepygments_1_1styles_1_1gh__dark" ],
    [ "gruvbox", "namespacepygments_1_1styles_1_1gruvbox.html", "namespacepygments_1_1styles_1_1gruvbox" ],
    [ "igor", "namespacepygments_1_1styles_1_1igor.html", "namespacepygments_1_1styles_1_1igor" ],
    [ "inkpot", "namespacepygments_1_1styles_1_1inkpot.html", "namespacepygments_1_1styles_1_1inkpot" ],
    [ "lightbulb", "namespacepygments_1_1styles_1_1lightbulb.html", "namespacepygments_1_1styles_1_1lightbulb" ],
    [ "lilypond", "namespacepygments_1_1styles_1_1lilypond.html", "namespacepygments_1_1styles_1_1lilypond" ],
    [ "lovelace", "namespacepygments_1_1styles_1_1lovelace.html", "namespacepygments_1_1styles_1_1lovelace" ],
    [ "manni", "namespacepygments_1_1styles_1_1manni.html", "namespacepygments_1_1styles_1_1manni" ],
    [ "material", "namespacepygments_1_1styles_1_1material.html", "namespacepygments_1_1styles_1_1material" ],
    [ "monokai", "namespacepygments_1_1styles_1_1monokai.html", "namespacepygments_1_1styles_1_1monokai" ],
    [ "murphy", "namespacepygments_1_1styles_1_1murphy.html", "namespacepygments_1_1styles_1_1murphy" ],
    [ "native", "namespacepygments_1_1styles_1_1native.html", "namespacepygments_1_1styles_1_1native" ],
    [ "nord", "namespacepygments_1_1styles_1_1nord.html", "namespacepygments_1_1styles_1_1nord" ],
    [ "onedark", "namespacepygments_1_1styles_1_1onedark.html", "namespacepygments_1_1styles_1_1onedark" ],
    [ "paraiso_dark", "namespacepygments_1_1styles_1_1paraiso__dark.html", "namespacepygments_1_1styles_1_1paraiso__dark" ],
    [ "paraiso_light", "namespacepygments_1_1styles_1_1paraiso__light.html", "namespacepygments_1_1styles_1_1paraiso__light" ],
    [ "pastie", "namespacepygments_1_1styles_1_1pastie.html", "namespacepygments_1_1styles_1_1pastie" ],
    [ "perldoc", "namespacepygments_1_1styles_1_1perldoc.html", "namespacepygments_1_1styles_1_1perldoc" ],
    [ "rainbow_dash", "namespacepygments_1_1styles_1_1rainbow__dash.html", "namespacepygments_1_1styles_1_1rainbow__dash" ],
    [ "rrt", "namespacepygments_1_1styles_1_1rrt.html", "namespacepygments_1_1styles_1_1rrt" ],
    [ "sas", "namespacepygments_1_1styles_1_1sas.html", "namespacepygments_1_1styles_1_1sas" ],
    [ "solarized", "namespacepygments_1_1styles_1_1solarized.html", "namespacepygments_1_1styles_1_1solarized" ],
    [ "staroffice", "namespacepygments_1_1styles_1_1staroffice.html", "namespacepygments_1_1styles_1_1staroffice" ],
    [ "stata_dark", "namespacepygments_1_1styles_1_1stata__dark.html", "namespacepygments_1_1styles_1_1stata__dark" ],
    [ "stata_light", "namespacepygments_1_1styles_1_1stata__light.html", "namespacepygments_1_1styles_1_1stata__light" ],
    [ "tango", "namespacepygments_1_1styles_1_1tango.html", "namespacepygments_1_1styles_1_1tango" ],
    [ "trac", "namespacepygments_1_1styles_1_1trac.html", "namespacepygments_1_1styles_1_1trac" ],
    [ "vim", "namespacepygments_1_1styles_1_1vim.html", "namespacepygments_1_1styles_1_1vim" ],
    [ "vs", "namespacepygments_1_1styles_1_1vs.html", "namespacepygments_1_1styles_1_1vs" ],
    [ "xcode", "namespacepygments_1_1styles_1_1xcode.html", "namespacepygments_1_1styles_1_1xcode" ],
    [ "zenburn", "namespacepygments_1_1styles_1_1zenburn.html", "namespacepygments_1_1styles_1_1zenburn" ],
    [ "get_all_styles", "namespacepygments_1_1styles.html#a826df533ddf34b79cdcc3c001e1d6c7b", null ],
    [ "get_style_by_name", "namespacepygments_1_1styles.html#a075d0a21658450f724edbfa0c3bd0d18", null ],
    [ "_STYLE_NAME_TO_MODULE_MAP", "namespacepygments_1_1styles.html#a0543c73bf2062827f206a392c964cc11", null ],
    [ "STYLE_MAP", "namespacepygments_1_1styles.html#ab40048d6e991b779ec0100a184efdaec", null ]
];