var namespacepip_1_1__vendor =
[
    [ "cachecontrol", "namespacepip_1_1__vendor_1_1cachecontrol.html", "namespacepip_1_1__vendor_1_1cachecontrol" ],
    [ "certifi", "namespacepip_1_1__vendor_1_1certifi.html", "namespacepip_1_1__vendor_1_1certifi" ],
    [ "dependency_groups", "namespacepip_1_1__vendor_1_1dependency__groups.html", "namespacepip_1_1__vendor_1_1dependency__groups" ],
    [ "distlib", "namespacepip_1_1__vendor_1_1distlib.html", "namespacepip_1_1__vendor_1_1distlib" ],
    [ "distro", "namespacepip_1_1__vendor_1_1distro.html", "namespacepip_1_1__vendor_1_1distro" ],
    [ "idna", "namespacepip_1_1__vendor_1_1idna.html", "namespacepip_1_1__vendor_1_1idna" ],
    [ "msgpack", "namespacepip_1_1__vendor_1_1msgpack.html", "namespacepip_1_1__vendor_1_1msgpack" ],
    [ "packaging", "namespacepip_1_1__vendor_1_1packaging.html", "namespacepip_1_1__vendor_1_1packaging" ],
    [ "pkg_resources", "namespacepip_1_1__vendor_1_1pkg__resources.html", "namespacepip_1_1__vendor_1_1pkg__resources" ],
    [ "platformdirs", "namespacepip_1_1__vendor_1_1platformdirs.html", "namespacepip_1_1__vendor_1_1platformdirs" ],
    [ "pygments", "namespacepip_1_1__vendor_1_1pygments.html", "namespacepip_1_1__vendor_1_1pygments" ],
    [ "pyproject_hooks", "namespacepip_1_1__vendor_1_1pyproject__hooks.html", "namespacepip_1_1__vendor_1_1pyproject__hooks" ],
    [ "requests", "namespacepip_1_1__vendor_1_1requests.html", "namespacepip_1_1__vendor_1_1requests" ],
    [ "resolvelib", "namespacepip_1_1__vendor_1_1resolvelib.html", "namespacepip_1_1__vendor_1_1resolvelib" ],
    [ "rich", "namespacepip_1_1__vendor_1_1rich.html", "namespacepip_1_1__vendor_1_1rich" ],
    [ "tomli", "namespacepip_1_1__vendor_1_1tomli.html", "namespacepip_1_1__vendor_1_1tomli" ],
    [ "tomli_w", "namespacepip_1_1__vendor_1_1tomli__w.html", "namespacepip_1_1__vendor_1_1tomli__w" ],
    [ "truststore", "namespacepip_1_1__vendor_1_1truststore.html", "namespacepip_1_1__vendor_1_1truststore" ],
    [ "urllib3", "namespacepip_1_1__vendor_1_1urllib3.html", "namespacepip_1_1__vendor_1_1urllib3" ],
    [ "vendored", "namespacepip_1_1__vendor.html#ad4213c10538d5321c960edd0daf4557d", null ],
    [ "DEBUNDLED", "namespacepip_1_1__vendor.html#a930323aa8adfd8f8930c466eac190266", null ],
    [ "WHEEL_DIR", "namespacepip_1_1__vendor.html#af8bd31398248323cdf81be83bf416c4b", null ]
];