var sqlparse_2sql_8py =
[
    [ "sqlparse.sql.NameAliasMixin", "classsqlparse_1_1sql_1_1_name_alias_mixin.html", "classsqlparse_1_1sql_1_1_name_alias_mixin" ],
    [ "sqlparse.sql.Token", "classsqlparse_1_1sql_1_1_token.html", "classsqlparse_1_1sql_1_1_token" ],
    [ "sqlparse.sql.TokenList", "classsqlparse_1_1sql_1_1_token_list.html", "classsqlparse_1_1sql_1_1_token_list" ],
    [ "sqlparse.sql.Statement", "classsqlparse_1_1sql_1_1_statement.html", "classsqlparse_1_1sql_1_1_statement" ],
    [ "sqlparse.sql.Identifier", "classsqlparse_1_1sql_1_1_identifier.html", "classsqlparse_1_1sql_1_1_identifier" ],
    [ "sqlparse.sql.IdentifierList", "classsqlparse_1_1sql_1_1_identifier_list.html", "classsqlparse_1_1sql_1_1_identifier_list" ],
    [ "sqlparse.sql.TypedLiteral", "classsqlparse_1_1sql_1_1_typed_literal.html", "classsqlparse_1_1sql_1_1_typed_literal" ],
    [ "sqlparse.sql.Parenthesis", "classsqlparse_1_1sql_1_1_parenthesis.html", "classsqlparse_1_1sql_1_1_parenthesis" ],
    [ "sqlparse.sql.SquareBrackets", "classsqlparse_1_1sql_1_1_square_brackets.html", "classsqlparse_1_1sql_1_1_square_brackets" ],
    [ "sqlparse.sql.Assignment", "classsqlparse_1_1sql_1_1_assignment.html", null ],
    [ "sqlparse.sql.If", "classsqlparse_1_1sql_1_1_if.html", "classsqlparse_1_1sql_1_1_if" ],
    [ "sqlparse.sql.For", "classsqlparse_1_1sql_1_1_for.html", "classsqlparse_1_1sql_1_1_for" ],
    [ "sqlparse.sql.Comparison", "classsqlparse_1_1sql_1_1_comparison.html", "classsqlparse_1_1sql_1_1_comparison" ],
    [ "sqlparse.sql.Comment", "classsqlparse_1_1sql_1_1_comment.html", "classsqlparse_1_1sql_1_1_comment" ],
    [ "sqlparse.sql.Where", "classsqlparse_1_1sql_1_1_where.html", "classsqlparse_1_1sql_1_1_where" ],
    [ "sqlparse.sql.Over", "classsqlparse_1_1sql_1_1_over.html", "classsqlparse_1_1sql_1_1_over" ],
    [ "sqlparse.sql.Having", "classsqlparse_1_1sql_1_1_having.html", "classsqlparse_1_1sql_1_1_having" ],
    [ "sqlparse.sql.Case", "classsqlparse_1_1sql_1_1_case.html", "classsqlparse_1_1sql_1_1_case" ],
    [ "sqlparse.sql.Function", "classsqlparse_1_1sql_1_1_function.html", "classsqlparse_1_1sql_1_1_function" ],
    [ "sqlparse.sql.Begin", "classsqlparse_1_1sql_1_1_begin.html", "classsqlparse_1_1sql_1_1_begin" ],
    [ "sqlparse.sql.Operation", "classsqlparse_1_1sql_1_1_operation.html", null ],
    [ "sqlparse.sql.Values", "classsqlparse_1_1sql_1_1_values.html", null ],
    [ "sqlparse.sql.Command", "classsqlparse_1_1sql_1_1_command.html", null ]
];